languageCode = "en-us"
title = "Kiali"
theme = "kiali"
baseURL = "https://kiali.io"
relativeURLs = true

[params]
    custom_css = [
      "/css/kiali_style.css",
      "https://use.fontawesome.com/releases/v5.3.1/css/all.css"
    ]
    maxBlogPosts   = 10

[menu]
  [[menu.main]]
      identifier = "main_features"
      name = "Features"
      url = "/documentation/latest/features"
      weight = 1
  [[menu.main]]
      identifier = "main_news"
      name = "News"
      url = "/news"
      weight = 2
      [[menu.main]]
          identifier = "news_security"
          name = "Security Bulletins"
          url = "/news/security-bulletins"
          weight = 1
          parent = "main_news"
      [[menu.main]]
          identifier = "news_relnotes"
          name = "Release Notes"
          url = "/news/release-notes"
          weight = 2
          parent = "main_news"
  [[menu.main]]
      identifier = "main_gettingstarted"
      name = "Getting Started"
      url = "/documentation/latest/getting-started"
      weight = 3
  [[menu.main]]
      identifier = "main_contribute"
      name = "Contribute"
      url = "/contribute"
      weight = 4
  [[menu.main]]
      identifier = "main_doc"
      name = "Documentation"
      url = "/documentation"
      weight = 5
  [[menu.main]]
      identifier = "main_faq"
      name = "FAQ"
      url = "/faq"
      weight = 6
